Cargo.lock
Cargo.toml
config/meta.toml
src/meta/mod.rs
src/meta/proto/meta.proto
src/meta/proto/meta.rs
src/meta/proto/mod.rs
src/meta/server.rs
src/meta/storage.rs
src/server.rs

[grpc server dev](https://github.com/robustmq/robustmq/commit/560f91253e05e247db501486a659b6b1649557b2)

grpc server dev

---

.github/workflows/rust.yml

close test

---

.github/workflows/rust.yml

RBIP-02: MQTT Broker's authentication and authorization mechanism supports a variety of data sources

---

.github/workflows/close-issues-on-merge.yml
config/example/cluster/mqtt-server/node-1.toml
config/example/cluster/mqtt-server/node-2.toml
config/example/cluster/mqtt-server/node-3.toml
config/example/cluster/placement-center/node-1.toml
config/example/cluster/placement-center/node-2.toml
config/example/cluster/placement-center/node-3.toml
config/example/cluster/storage-engine/node-1.toml
config/example/cluster/storage-engine/node-2.toml
config/example/cluster/storage-engine/node-3.toml
src/mqtt-broker/src/security/mysql/mod.rs
src/mqtt-broker/src/security/mysql/schema.rs
src/mqtt-broker/src/security/mysql/sql.sql

RBIP-08: MQTT Broker permission module with support for MySQL data sources 

---

config/example/cluster/mqtt-server/node-1.toml

RBIP-01: MQTT Broker supports flow control

---

.github/workflows/rust.yml
makefile
nohup.out
scripts/integration-testing.sh
scripts/test_case.sh
src/mqtt-broker/tests/mqtt_client_test.rs
tests/config/journal-server.toml
tests/config/mqtt-server.toml
tests/config/placement-center.toml

RBIP-09：A makefile for writing integration tests

---

src/common/metadata-struct/src/mqtt/cluster.rs
src/mqtt-broker/src/handler/cache_manager.rs
src/mqtt-broker/src/handler/pkid.rs
src/mqtt-broker/src/server/connection_manager.rs
src/mqtt-broker/tests/client_test.rs
src/mqtt-broker/tests/common.rs
src/mqtt-broker/tests/connect_test.rs

RBIP-11: MQTT client is written using paho-mqtt to test the correctness of the Broker function on the MQTT protocol

---

src/mqtt-broker/tests/common.rs
src/mqtt-broker/tests/connect_test.rs
src/mqtt-broker/tests/publish_test.rs
src/mqtt-broker/tests/subscribe34_test.rs
src/mqtt-broker/tests/subscribe5_test.rs

RBIP-12: Complete functional test cases for the client perspective of the Publish command in MQTT3/4/5

---

src/mqtt-broker/src/handler/cache.rs
src/mqtt-broker/src/handler/constant.rs
src/mqtt-broker/src/handler/mod.rs
src/mqtt-broker/src/handler/retain.rs
src/mqtt-broker/src/security/mod.rs
src/mqtt-broker/src/security/placement/mod.rs
src/mqtt-broker/tests/retain_message_test.rs
src/placement-center/src/raft/route/cluster.rs
src/placement-center/src/storage/mqtt/acl.rs

MINOR：MQTT Broker supplements the retention message test case

---

config/log4rs.yaml
src/clients/src/broker_mqtt/call.rs
src/common/metadata-struct/src/acl/mod.rs
src/common/metadata-struct/src/mqtt/lastwill.rs
src/mqtt-broker/src/handler/constant.rs
src/mqtt-broker/src/handler/lastwill.rs
src/mqtt-broker/src/handler/mqtt.rs
src/mqtt-broker/src/handler/topic.rs
src/mqtt-broker/src/lib.rs
src/mqtt-broker/src/server/connection_manager.rs
src/mqtt-broker/src/server/grpc/services.rs
src/mqtt-broker/src/server/tcp/server.rs
src/mqtt-broker/tests/lastwill_message_test.rs
src/mqtt-broker/tests/retain_message_test.rs
src/mqtt-broker/tests/topic_alias_test.rs
src/mqtt-broker/tests/user_properties_test.rs
src/placement-center/src/controller/mqtt/call_broker.rs
src/placement-center/src/controller/mqtt/session_expire.rs

MINOR: MQTT Broker supplements the Will message test case

---

src/clients/tests/mqtt_user_test.rs
src/common/metadata-struct/src/mqtt/user.rs
src/mqtt-broker/src/storage/user.rs
src/placement-center/src/server/grpc/service_mqtt.rs
src/protocol/src/placement_center/generate/mqtt.rs
src/protocol/src/placement_center/proto/mqtt.proto

close #385  rename ListUserRequest 'username' to 'user_name'

---

src/clients/tests/mod.rs
src/clients/tests/mqtt/mod.rs
src/clients/tests/mqtt/mqtt_acl_test.rs
src/clients/tests/mqtt/mqtt_blacklist_test.rs
src/clients/tests/mqtt/mqtt_session_test.rs
src/clients/tests/mqtt/mqtt_topic_test.rs
src/clients/tests/mqtt/mqtt_user_test.rs
src/common/metadata-struct/src/mqtt/topic.rs

close #391

---

src/clients/tests/mqtt/mod.rs
src/clients/tests/mqtt/mqtt_last_will_test.rs

close #397

---

src/protocol/src/placement_center/generate/mqtt.rs
src/protocol/src/placement_center/proto/mqtt.proto

close #408

---

src/mqtt-broker/src/security/acl/metadata.rs

add acl_metadata_test

---

docs/cn/系统架构/配置说明/mqtt-server.md
docs/cn/系统架构/配置说明/placement-center.md

docs: configuration documentation

---

docs/en/ Introduction/What is RobustMQ.md

Add English document

---

Cargo.lock
src/cli-command/Cargo.toml
src/cli-command/src/lib.rs
src/cli-command/src/mqtt.rs
src/cli-command/src/placement.rs
src/clients/src/mqtt/admin/call.rs
src/mqtt-broker/src/server/grpc/admin/services.rs
src/placement-center/src/raft/machine.rs
src/placement-center/src/raft/metadata.rs

feat:  command-line tool supports' robustctl-mqtt status' to view broker node status 

---

rustfmt.toml
src/mqtt-broker/tests/common.rs
src/mqtt-broker/tests/connect_test.rs
src/mqtt-broker/tests/req_resp_test.rs

test:  fix MQTT Broker supports test cases for Request/Response features

---

src/mqtt-broker/tests/share_sub_test.rs

test: MQTT Broker supplements the Share Subscriptions test case

---

src/mqtt-broker/tests/common.rs
src/mqtt-broker/tests/connect_test.rs

test: Add MQTT broker WebSocket connection test

---

src/clients/src/placement/placement/mod.rs
src/clients/src/poll.rs
src/journal-server/src/server/tcp/connection.rs
src/mqtt-broker/src/handler/connection.rs
src/mqtt-broker/src/server/connection_manager.rs
src/mqtt-broker/src/server/tcp/response.rs
src/mqtt-broker/src/server/websocket/server.rs

fix: fix network bug

---

scripts/integration-testing.sh

fix: fix test cases

---

.github/workflows/rust-testing.yml
scripts/integration-testing.sh
src/cli-command/src/lib.rs

test: test pr

---

src/cli-command/src/mqtt.rs

test: test case

---

.github/workflows/rust-testing.yml
src/cli-command/src/mqtt.rs

test: test test

---

src/clients/src/mqtt/admin/inner.rs
src/clients/src/mqtt/admin/mod.rs
src/clients/src/mqtt/placement/inner.rs
src/clients/src/mqtt/placement/mod.rs
src/clients/src/placement/journal/inner.rs
src/clients/src/placement/journal/mod.rs
src/clients/src/placement/kv/inner.rs
src/clients/src/placement/kv/mod.rs
src/clients/src/placement/mqtt/inner.rs
src/clients/src/placement/mqtt/mod.rs
src/clients/src/placement/placement/inner.rs
src/clients/src/placement/placement/mod.rs
src/clients/src/poll.rs
src/mqtt-broker/src/storage/topic.rs
src/placement-center/src/raft/metadata.rs

fix: Fixed connection pool bugs

---

src/clients/src/poll.rs
src/mqtt-broker/src/handler/cache.rs
src/mqtt-broker/src/handler/retain.rs
src/mqtt-broker/src/storage/topic.rs
src/mqtt-broker/src/subscribe/sub_exclusive.rs
src/mqtt-broker/src/subscribe/sub_share_leader.rs
src/mqtt-broker/src/subscribe/subscribe_manager.rs
src/mqtt-broker/src/subscribe/subscriber.rs
src/placement-center/tests/broker_heartbeat_test.rs

fix: Fixed subscription bugs

---

src/mqtt-broker/tests/sub_identifier.rs

test: add subscribe identifier

---

src/mqtt-broker/tests/common.rs
src/mqtt-broker/tests/connect_packet_size_test.rs
src/mqtt-broker/tests/connect_test.rs
src/mqtt-broker/tests/lastwill_message_test.rs
src/mqtt-broker/tests/pub_qos_test.rs
src/mqtt-broker/tests/req_resp_test.rs
src/mqtt-broker/tests/retain_message_test.rs
src/mqtt-broker/tests/share_sub_test.rs
src/mqtt-broker/tests/sub5_qos_test.rs
src/mqtt-broker/tests/sub_identifier.rs
src/mqtt-broker/tests/topic_alias_test.rs

test: fix subscribe identifier

---

src/clients/src/placement/mod.rs
src/clients/src/placement/mqtt/call.rs
src/clients/src/placement/mqtt/inner.rs
src/clients/src/placement/mqtt/mod.rs
src/placement-center/src/lib.rs
src/placement-center/src/server/grpc/service_mqtt.rs
src/protocol/src/placement_center/generate/mqtt.rs
src/protocol/src/placement_center/proto/mqtt.proto

- mqtt interface: CreateUser, DeleteUser, CreateTopic, DeleteTopic, CreateSession, DeleteSession, UpdateSession, DeleteSession, CreateAcl, DeleteAcl, CreateBlackList, DeleteBlackList receives a write request and will be forwarded to the leader node of the placement center at the client.
close #402

feat: Placement center node receives a write request to be forwarded to the Leader node for processing

---

scripts/integration-testing.sh
src/mqtt-broker/src/server/websocket/server.rs
src/mqtt-broker/src/storage/topic.rs
src/mqtt-broker/src/subscribe/sub_common.rs
src/mqtt-broker/tests/common.rs
src/mqtt-broker/tests/connect_packet_size_test.rs
src/mqtt-broker/tests/sub5_qos_test.rs
src/mqtt-broker/tests/sub_identifier_test.rs
src/placement-center/src/raft/metadata.rs
src/placement-center/tests/common.rs
src/protocol/src/mqtt/common.rs

test: test 

---

README.md

fix: the QR Code expired, can't join Wechat Group

---

rustfmt.toml
src/clients/src/placement/mod.rs
src/mqtt-broker/tests/sub_identifier_test.rs
src/placement-center/src/raft/apply.rs
src/placement-center/src/raft/route/cluster.rs
src/placement-center/src/raft/route/mod.rs
src/placement-center/src/server/grpc/service_placement.rs

test: fix test bug

---

src/protocol/src/broker_server/generate/admin.rs
src/protocol/src/broker_server/generate/placement.rs
src/protocol/src/journal_server/generate/protocol/fetch.rs
src/protocol/src/journal_server/generate/protocol/header.rs
src/protocol/src/journal_server/generate/protocol/produce.rs
src/protocol/src/journal_server/generate/record/record.rs
src/protocol/src/placement_center/generate/common.rs
src/protocol/src/placement_center/generate/journal.rs
src/protocol/src/placement_center/generate/kv.rs
src/protocol/src/placement_center/generate/mqtt.rs
src/protocol/src/placement_center/generate/placement.rs
src/protocol/src/placement_center/proto/common.proto

This is the task list for adding comments to common.proto for the placement_center as part of the "RobustMQ good first issue."
Thanks!
I'll start learning rust from the PR of robustmq.

MINOR: Add comments to placement_center's common.proto

---

src/placement-center/src/storage/placement/cluster.rs

This PR adds comments to src/placement-center/src/storage/placement/cluster.rs as part of the "RobustMQ good first issue."
I am a beginner in Rust and I'm very interested in contributing to this message queue project. This is my first issue, and I'm eager to learn and help improve the project. Additionally, I noticed that the WeChat group QR code is no longer valid, and I would appreciate it if it could be updated so I can join the group.
Thank you for the opportunity to contribute!

MINOR: Add comments to storage/placement/cluster.rs

---

src/clients/tests/kv_test.rs
src/mqtt-broker/src/storage/cluster.rs

Add validation to the Set method in the GrpcKvService file
- https://github.com/robustmq/robustmq/issues/487

test: Add validation to the Set method in the GrpcKvService file

---

src/mqtt-broker/src/lib.rs
src/mqtt-broker/src/storage/cluster.rs

- Update param to register_node and unregister_node
- Refine the cluster_node_test test case in src/mqtt-broker/src/storage/cluster.rs
close #440

fix: Add &BrokerMQTTConfig param to register_node and unregister_node functions and refine the cluster_node_test test case

---

src/protocol/src/lib.rs
src/protocol/src/mqtt/common.rs
src/protocol/src/mqtt/mqttv4/connack.rs
src/protocol/src/mqtt/mqttv4/connect.rs
src/protocol/src/mqtt/mqttv4/disconnect.rs
src/protocol/src/mqtt/mqttv4/mod.rs
src/protocol/src/mqtt/mqttv4/ping.rs
src/protocol/src/mqtt/mqttv4/puback.rs
src/protocol/src/mqtt/mqttv4/pubcomp.rs
src/protocol/src/mqtt/mqttv4/publish.rs
src/protocol/src/mqtt/mqttv4/pubrec.rs
src/protocol/src/mqtt/mqttv4/pubrel.rs
src/protocol/src/mqtt/mqttv4/suback.rs
src/protocol/src/mqtt/mqttv4/subscribe.rs
src/protocol/src/mqtt/mqttv4/unsuback.rs
src/protocol/src/mqtt/mqttv4/unsubscribe.rs
src/protocol/src/mqtt/mqttv5/connack.rs
src/protocol/src/mqtt/mqttv5/connect.rs
src/protocol/src/mqtt/mqttv5/disconnect.rs
src/protocol/src/mqtt/mqttv5/mod.rs
src/protocol/src/mqtt/mqttv5/ping.rs
src/protocol/src/mqtt/mqttv5/puback.rs
src/protocol/src/mqtt/mqttv5/pubcomp.rs
src/protocol/src/mqtt/mqttv5/publish.rs
src/protocol/src/mqtt/mqttv5/pubrec.rs
src/protocol/src/mqtt/mqttv5/pubrel.rs
src/protocol/src/mqtt/mqttv5/suback.rs
src/protocol/src/mqtt/mqttv5/subscribe.rs
src/protocol/src/mqtt/mqttv5/unsuback.rs
src/protocol/src/mqtt/mqttv5/unsubscribe.rs

fix: Remove redundant comments

---

src/mqtt-broker/src/handler/cache.rs
src/mqtt-broker/src/handler/retain.rs
src/mqtt-broker/tests/sub_options_test.rs

- fix: cache_manager.is_new_sub in retain::try_send_retain_message always return false
- feat: MQTT Broker supplements the Subscription Options test case
close https://github.com/robustmq/robustmq/issues/360

feat: MQTT Broker supplements the Subscription Options test case and fix a bug

---

src/grpc-clients/tests/placement_test.rs
src/placement-center/src/server/grpc/service_placement.rs
src/placement-center/src/server/grpc/validate.rs

test: Add validation to the set_resource_config method in GrpcPlacementService and fill in the test case

---

src/placement-center/src/server/grpc/service_placement.rs
src/placement-center/src/server/grpc/validate.rs
src/placement-center/tests/common.rs
src/placement-center/tests/grpc_clients_test.rs

refactor: Add validation to the set_idempotent_data method in cementService and fill in the test case
close #545

refactor: Add validation to the set_idempotent_data method in cementService and fill in the test case

---

src/protocol/src/mqtt/codec.rs
src/protocol/src/mqtt/common.rs
src/protocol/src/mqtt/mqttv4/codec.rs
src/protocol/src/mqtt/mqttv5/auth.rs
src/protocol/src/mqtt/mqttv5/codec.rs
src/protocol/src/mqtt/mqttv5/mod.rs

- Add Auth packet (15)
close #281

feat: Add Auth packet(15)

---

src/common/metadata-struct/src/journal/segment.rs
src/grpc-clients/src/journal/admin/call.rs
src/grpc-clients/src/journal/admin/mod.rs
src/grpc-clients/src/journal/mod.rs
src/journal-server/src/core/cache.rs
src/journal-server/src/core/write.rs
src/journal-server/src/handler/shard.rs
src/journal-server/src/lib.rs
src/journal-server/src/segment/manager.rs
src/journal-server/src/segment/status.rs
src/journal-server/src/server/grpc/admin.rs
src/journal-server/src/server/grpc/server.rs
src/placement-center/src/journal/services/segmet.rs
src/placement-center/src/journal/services/shard.rs
src/protocol/src/journal_server/proto/admin.proto
src/protocol/src/journal_server/proto/engine.proto
tests/tests/journal_server/common.rs
tests/tests/journal_server/grpc_admin.rs
tests/tests/journal_server/mod.rs

feat: Journal reading and writing process development

---

.github/actions/setup-builder/action.yaml
.github/workflows/code-style.yml
.github/workflows/license.yaml
.github/workflows/place-ig-test.yml
.github/workflows/unit-test.yml
.gitignore
deny.toml
scripts/unit-test.sh

integrate CI with pre-commit checks
no related

ci: Integrate CI with pre-commit checks.

---

README.md
docs/cn/系统架构/测试用例.md
makefile

docs: Update CN README and docs

---

scripts/unit-test.sh
src/grpc-clients/tests/placement/mqtt/cluster_test.rs
src/placement-center/src/server/grpc/service_placement.rs
src/placement-center/src/server/grpc/validate.rs

refactor: #542 add validation to the get resource config method in grpc placement service

---

Cargo.lock
config/log4rs.yaml
src/common/metadata-struct/Cargo.toml
src/common/metadata-struct/src/mqtt/connection.rs
src/common/metadata-struct/src/mqtt/mod.rs
src/journal-server/src/segment/scroll.rs
src/mqtt-broker/src/handler/cache.rs
src/mqtt-broker/src/handler/connection.rs
src/mqtt-broker/src/handler/keep_alive.rs
src/mqtt-broker/src/handler/response.rs
src/mqtt-broker/src/handler/validator.rs
src/mqtt-broker/src/observability/system_topic/event.rs
src/mqtt-broker/src/security/acl/mod.rs
src/mqtt-broker/src/security/mod.rs
src/protocol/src/broker_mqtt/proto/admin.proto

refactor: Optimize the MQTT Connection structure

---

src/journal-server/src/core/cluster.rs
src/journal-server/src/core/error.rs
src/journal-server/src/core/segment_meta.rs
src/journal-server/src/handler/command.rs
src/journal-server/src/handler/data.rs
src/journal-server/src/index/build.rs
src/journal-server/src/index/keys.rs
src/journal-server/src/index/mod.rs
src/journal-server/src/index/offset.rs
src/journal-server/src/index/tag.rs
src/journal-server/src/index/time.rs
src/journal-server/src/lib.rs
src/journal-server/src/segment/file.rs
src/journal-server/src/segment/read.rs
src/journal-server/src/segment/write.rs
src/placement-center/src/server/grpc/service_placement.rs
src/protocol/src/journal_server/proto/engine.proto
tests/tests/journal_client/base_test.rs
tests/tests/journal_client/data_test.rs

refactor:  Read data according to Offset/Timestamp/Tag/Key

---

src/grpc-clients/src/mqtt/placement/call.rs
src/grpc-clients/src/mqtt/placement/inner.rs
src/grpc-clients/src/mqtt/placement/mod.rs
src/journal-client/src/cache.rs
src/journal-client/src/connection.rs
src/journal-client/src/lib.rs
src/journal-client/src/option.rs
src/journal-server/src/core/cache.rs
src/journal-server/src/core/mod.rs
src/journal-server/src/core/notification.rs
src/journal-server/src/core/segment_meta.rs
src/journal-server/src/core/segment_status.rs
src/journal-server/src/handler/data.rs
src/journal-server/src/segment/manager.rs
src/journal-server/src/segment/read.rs
src/journal-server/src/segment/scroll.rs
src/journal-server/src/segment/write.rs
src/journal-server/src/server/grpc/inner.rs
src/mqtt-broker/src/handler/cache.rs
src/mqtt-broker/src/server/grpc/inner.rs
src/mqtt-broker/src/server/grpc/mod.rs
src/mqtt-broker/src/server/grpc/server.rs
src/placement-center/src/mqtt/controller/call_broker.rs
src/protocol/build.rs
src/protocol/src/broker_mqtt/mod.rs
src/protocol/src/broker_mqtt/proto/inner.proto
tests/tests/journal_client/common.rs
tests/tests/journal_client/data_test.rs

refactor: Partial code optimization

---

_typos.toml
src/mqtt-broker/src/observability/metrics/packets.rs

_Update excluded typo UNSUBSCRIBE_
- Update excluded typo UNSUBSCRIBE in order to get all checklist passed

fix: update excluded typo

---

src/mqtt-broker/src/observability/metrics/packets.rs

_add metrics_packets_sent_
- add metrics_packets_sent
#283

feat: add metrics_packets_sent

---

src/mqtt-broker/src/observability/metrics/packets.rs

_Add metrics packets_connack_auth_error_
- Add metrics packets_connack_auth_error
#283

feat: Add metrics packets_connack_auth_error

---

.github/actions/setup-builder/action.yaml
.github/workflows/code-style.yml
src/placement-center/src/core/heartbeat.rs

ci: fix ci rust version

---

src/placement-center/src/server/http/index.rs
src/placement-center/src/server/http/server.rs

- Add raft_metrics function to collect and format Raft metrics data
- Update routes to include new RAFT_METRICS endpoint

feat: add raft metrics endpoint- Implement new endpoint for Raft metrics

---

tests/tests/mqtt_protocol/common.rs
tests/tests/mqtt_protocol/mod.rs
tests/tests/mqtt_protocol/pub_qos_test.rs
tests/tests/mqtt_protocol/sub34_qos_test.rs
tests/tests/mqtt_protocol/ws_sub_pub_test.rs
tests/tests/mqtt_protocol/wss_sub_pub_test.rs

test: Add pub/sub test cases for ws/wss.

---

src/journal-client/src/error.rs
src/journal-client/src/reader.rs
src/journal-client/src/writer.rs
src/mqtt-broker/src/subscribe/subscribe_manager.rs
src/storage-adapter/src/journal/mod.rs
src/storage-adapter/src/journal/offset.rs
tests/tests/mqtt_protocol/share_sub_test.rs

feat: Optimize the journal client code

---

src/journal-client/src/cache.rs
src/journal-client/src/connection.rs
src/journal-client/src/error.rs
src/journal-client/src/lib.rs
src/journal-client/src/reader.rs
src/journal-client/src/writer.rs

feat: Journa Client code optimization

---

src/placement-center/src/lib.rs

- Implement monitoring of raft leader transitions
- Add function to watch for changes in raft metrics

feat(placement-center): monitor leader transitions in raft

---

.github/workflows/deployment-vite.yml
docs/.vitepress/config.mts
docs/.vitepress/src/theme.mts
docs/en/index.md
docs/index.md

build: build vitepress for robustmq

---

docs/zh/ContributionGuide/Github-Pull-Request-Example.md

Add an example of modifying code and creating a pull request (PR)

docs: Quick guide doc

---

example/mqtt-cluster/placement-center/node-1.toml
scripts/journal-ig-test.sh
scripts/mqtt-ig-test.sh
scripts/place-ig-test.sh
src/journal-server/src/index/time.rs
src/journal-server/src/segment/file.rs
src/journal-server/src/segment/manager.rs
src/journal-server/src/segment/read.rs
src/journal-server/src/segment/write.rs
tests/tests/mqtt_protocol/sub_identifier_test.rs

test: Add the Journal Engine test case

---

src/journal-server/src/lib.rs

fix: Optimizing Code Warnings

---

src/mqtt-broker/src/observability/metrics/packets.rs

_add metrics packets.connack.error_
- add metrics packets.connack.error
#283

feat: add metrics packets.connack.error

---

docs/.design/logic/flapping-detect.md

describe the logic of flapping-detect simply.
relate #285

docs: add flapping-detect design logic

---

src/grpc-clients/tests/placement/mqtt/cluster_test.rs
src/placement-center/src/server/grpc/service_inner.rs
src/placement-center/src/server/grpc/validate.rs

close #540 
Add validation to `node_list` method (`cluster_name` should not be empty) and create test case `node_list_test`.

chore: Add validation to the node_list method & test

---

.github/ISSUE_TEMPLATE/umbrella.yml

As stated in the title
close #743

build: fix a template error in the placeholder of task list

---

src/storage-adapter/src/memory/mod.rs

relate #703 
Fill in empty functions in `storage-adapter/src/memory`

feat: Implement StorageAdapter for MemoryStorageAdapter

---

docs/.vitepress/src/sidebars/en.mts
docs/en/QuickGuide/Build.md
docs/en/QuickGuide/Overview.md
docs/en/RobustMQ-Command/Overview.md
docs/zh/QuickGuide/Build.md
docs/zh/RobustMQ-Command/Overview.md

doc: Optimizing the command documentation

---

docs/.design/logic/Integrate the metrics module.md
docs/.design/observability/metrics.md

add a example to integrate metrics in roubstmq from prometheus-client
close #776

docs: integrate metrics module examples

---

docs/en/QuickGuide/Run-Docker-Mode.md
docs/en/QuickGuide/Run-K8S-Mode.md
docs/zh/QuickGuide/Run-Docker-Mode.md
docs/zh/QuickGuide/Run-K8S-Mode.md
example/test-network-docker/compose/compose-test-net.yaml

1. Verified the functionality of docker mode
2. More detailed docker and k8s documentation

docs: More detailed docker and k8s documentation

---

README.md

add a tips for readme.md to told user and contributor that it is a preview project.

docs: add a tips for readme.md

---

README.md

Add a star history graph in README.md

docs: add star history graph in README.md

---

Cargo.lock
src/storage-adapter/Cargo.toml
src/storage-adapter/src/mysql/mod.rs

close #804 
Fixed concurrent bug. Add concurrency test for MySQL

fix: fix mysql offset bug

---

README.md

doc: Update the Readme.md

---

src/storage-adapter/src/rocksdb/mod.rs

Currently the throughput for rocksdb is not ideal. The performance test added in this PR reveal this issue.

perf: improve throughput for rocksdb

---

src/common/metadata-struct/src/journal/segment.rs
src/common/metadata-struct/src/journal/segment_meta.rs
src/journal-server/src/core/cache.rs
src/journal-server/src/segment/file.rs
src/journal-server/src/segment/manager.rs
src/journal-server/src/segment/mod.rs
src/journal-server/src/segment/read.rs
src/journal-server/src/segment/scroll.rs
src/journal-server/src/segment/write.rs

docs: add comments under src/journal-server and src/common/metadata-struct

---

src/journal-server/src/core/shard.rs
src/journal-server/src/handler/command.rs
src/journal-server/src/server/connection.rs
src/journal-server/src/server/connection_manager.rs
src/journal-server/src/server/tcp/handler.rs
src/journal-server/src/server/tcp/response.rs
src/journal-server/src/server/tcp/server.rs
src/journal-server/src/server/tcp/tcp_server.rs

docs: add comments in journal server

---

Cargo.lock
Cargo.toml
src/common/base/Cargo.toml
src/common/base/src/error/common.rs
src/storage-adapter/Cargo.toml
src/storage-adapter/src/lib.rs
src/storage-adapter/src/minio/mod.rs

relate: #703 
Implement MinIO Storage Adapter

feat: Implement MinIO Storage Adapter

---

docs/.design/storage-adapter/minio.md

relate #825 
Optimize MinIO performance by redesigning a storage model and intercepting a cache layer.

perf: Optimize MinIO performance

---

config/log-config/mqtt-log4rs.yaml
config/log-config/place-log4rs.yaml
docs/.design/plan/mqtt-stable-to-do.md
example/mqtt-cluster/placement-center/node-1.toml
src/common/metadata-struct/src/mqtt/cluster.rs
src/mqtt-broker/src/handler/heartbreat.rs
src/mqtt-broker/src/handler/mqtt.rs
src/mqtt-broker/src/handler/retain.rs
src/mqtt-broker/src/handler/sub_exclusive.rs
src/mqtt-broker/src/handler/subscribe.rs
src/mqtt-broker/src/server/connection_manager.rs
src/mqtt-broker/src/server/websocket/server.rs
src/placement-center/src/core/controller.rs
src/placement-center/src/core/heartbeat.rs
src/placement-center/src/mqtt/controller/session_expire.rs
src/placement-center/src/server/grpc/service_inner.rs
tests/tests/mqtt_protocol/connect34_test.rs
tests/tests/mqtt_protocol/permission34_test.rs
tests/tests/mqtt_protocol/permission5_test.rs
tests/tests/mqtt_protocol/sub_exclusive_test.rs
tests/tests/mqtt_protocol/sub_options_test.rs

fix: Fixed mqtt protocol test case failures

---

bin/robust-server

there are no ut for startup script.  and here list my  test cmd 
```
bin/robust-server place start config/placement-center.toml
bin/robust-server place start 
bin/robust-server mqtt start config/mqtt-server.toml
bin/robust-server mqtt start 
bin/robust-server place stop
bin/robust-server mqtt stop
```
You can refer to the [GitHub …

refactor(startup shell): startup script bin/robust-server refactor . add more argument validation checks

---

docs/.design/plan/mqtt-stable-to-do.md
src/placement-center/src/lib.rs
src/placement-center/src/mqtt/controller/mod.rs
src/placement-center/src/mqtt/controller/session_expire.rs
src/placement-center/src/raft/leadership.rs
src/placement-center/src/raft/mod.rs
src/storage-adapter/src/lib.rs
src/storage-adapter/src/s3/mod.rs

feat: Optimization of Placement Center Leader switching logic

---

docs/.design/plan/mqtt-stable-to-do.md
docs/.vitepress/src/sidebars/en.mts
docs/.vitepress/src/sidebars/zh.mts
src/mqtt-broker/src/handler/delay_message.rs
src/mqtt-broker/src/handler/mod.rs
src/mqtt-broker/src/lib.rs

doc: Add MQTT documents

---

docs/en/QuickGuide/Run-Cluster-Mode.md
docs/en/QuickGuide/Run-Standalone-Mode.md
docs/zh/QuickGuide/Run-Cluster-Mode.md
docs/zh/QuickGuide/Run-Standalone-Mode.md

docs:tidy up doc in QuickGuide

---

docs/.vitepress/src/sidebars/en.mts
docs/.vitepress/src/sidebars/zh.mts
src/common/metadata-struct/src/mqtt/cluster.rs
src/mqtt-broker/src/bridge/mod.rs
src/mqtt-broker/src/handler/cache_update.rs
src/mqtt-broker/src/handler/cluster_config.rs
src/mqtt-broker/src/handler/connection.rs
src/mqtt-broker/src/handler/delay_message.rs
src/mqtt-broker/src/handler/session.rs
src/mqtt-broker/src/lib.rs
src/mqtt-broker/src/storage/cluster.rs
tests/tests/mqtt_server/cluster_storage_test.rs

feat: mqtt local configuration and dynamic configuration merge

---

src/cli-command/src/mqtt.rs
src/cmd/src/cli-command/command.rs
src/cmd/src/cli-command/mqtt/admin.rs
src/common/metadata-struct/src/mqtt/bridge/connector.rs
src/common/metadata-struct/src/mqtt/bridge/connector_type.rs
src/common/metadata-struct/src/mqtt/bridge/status.rs
src/grpc-clients/src/mqtt/admin/call.rs
src/grpc-clients/src/mqtt/admin/mod.rs

Add GRPC support for connector CLI commands.

feat: connector CLI GRPC

---

Cargo.lock
Cargo.toml
src/delay-message/src/build.rs
src/delay-message/src/lib.rs
src/delay-message/src/pop.rs
src/idempotent-message/Cargo.toml
src/idempotent-message/src/lib.rs
src/idempotent-message/tests/mod.rs
src/mqtt-broker/src/handler/command.rs
src/mqtt-broker/src/handler/delay_message.rs
src/mqtt-broker/src/handler/error.rs
src/mqtt-broker/src/handler/mqtt.rs
src/mqtt-broker/src/handler/offline_message.rs
src/mqtt-broker/src/lib.rs
src/mqtt-broker/src/server/tcp/server.rs
src/mqtt-broker/src/server/websocket/server.rs
src/storage-adapter/src/journal/mod.rs
src/storage-adapter/src/memory/mod.rs
src/storage-adapter/src/minio/mod.rs
src/storage-adapter/src/mysql/mod.rs
src/storage-adapter/src/rocksdb/mod.rs
src/storage-adapter/src/storage.rs

feat: MQTT supports the function of delayed message publishing

---

docs/.vitepress/src/sidebars/en.mts
docs/.vitepress/src/sidebars/zh.mts
docs/en/RobustMQ-MQTT/DelayMessage.md
docs/zh/RobustMQ-MQTT/DelayMessage.md

docs: Add delay message documentation

---

Cargo.lock
src/common/metadata-struct/src/schema.rs
src/grpc-clients/src/placement/inner/call.rs
src/grpc-clients/src/placement/inner/mod.rs
src/mqtt-broker/Cargo.toml
src/mqtt-broker/src/handler/cache_update.rs
src/mqtt-broker/src/handler/command.rs
src/mqtt-broker/src/handler/mqtt.rs
src/mqtt-broker/src/lib.rs
src/mqtt-broker/src/server/grpc/inner.rs
src/mqtt-broker/src/server/grpc/server.rs
src/mqtt-broker/src/server/tcp/server.rs
src/mqtt-broker/src/server/websocket/server.rs
src/placement-center/src/core/error.rs
src/placement-center/src/core/mod.rs
src/placement-center/src/core/schema.rs
src/placement-center/src/mqtt/controller/call_broker.rs
src/placement-center/src/route/common.rs
src/placement-center/src/route/data.rs
src/placement-center/src/route/mod.rs
src/placement-center/src/server/grpc/service_inner.rs
src/placement-center/src/storage/keys.rs
src/placement-center/src/storage/placement/mod.rs
src/placement-center/src/storage/placement/schema.rs
src/protocol/src/broker_mqtt/proto/inner.proto
src/protocol/src/placement_center/proto/inner.proto
src/schema-register/src/schema.rs

feat: MQTT Broker supports schema 

---

Cargo.lock
Cargo.toml
src/schema-register/Cargo.toml
src/schema-register/src/protobuf.rs

relate #892 
Add example usage of [protofish](https://docs.rs/protofish/0.5.2/protofish/).

feat: Add protofish tests

---

src/cli-command/src/mqtt.rs
src/cmd/src/cli-command/command.rs
src/cmd/src/cli-command/mqtt/admin.rs
src/common/metadata-struct/src/schema.rs
src/grpc-clients/src/mqtt/admin/call.rs
src/grpc-clients/src/mqtt/admin/mod.rs
src/grpc-clients/tests/mqtt/mqtt_admin_test.rs
src/grpc-clients/tests/placement/mqtt/mod.rs
src/grpc-clients/tests/placement/mqtt/mqtt_schema_test.rs
src/mqtt-broker/src/handler/cache_update.rs
src/mqtt-broker/src/handler/error.rs
src/mqtt-broker/src/lib.rs
src/mqtt-broker/src/server/grpc/admin.rs
src/mqtt-broker/src/server/grpc/server.rs
src/mqtt-broker/src/storage/mod.rs
src/mqtt-broker/src/storage/schema.rs
src/protocol/src/broker_mqtt/proto/admin.proto
src/schema-register/src/schema.rs

Add Mqtt-broker admin GPRC and CLI support.

feat: Add Mqtt-broker schema Admin GRPC and CLI

---

src/schema-register/src/protobuf.rs

relate #892 
Validate if the supplied protobuf bytes match a given protobuf schema.

feat: add validation for protobuf schema

---

src/cli-command/src/mqtt.rs

- update `list_connections` method std output like `list_slow_subscribe` method using prettytable.
- closes #881 
to submit the corresponding Issue.It also has an [PR …

refactor: refactor the list_connectors method.

---

src/common/metadata-struct/src/mqtt/bridge/connector_type.rs
src/grpc-clients/tests/mqtt/mqtt_admin_test.rs
src/grpc-clients/tests/placement/mqtt/mqtt_connector_test.rs
src/mqtt-broker/src/bridge/request.rs
src/mqtt-broker/src/server/grpc/admin.rs
src/mqtt-broker/src/server/grpc/server.rs
src/placement-center/src/mqtt/connector/request.rs

Add `connector_test` into MQTT integration test.

test: complete CRUD test for connector

---

src/grpc-clients/tests/mqtt/mqtt_admin_test.rs
src/grpc-clients/tests/placement/mqtt/mqtt_schema_test.rs
src/mqtt-broker/src/server/grpc/admin.rs
src/mqtt-broker/src/server/grpc/server.rs
src/mqtt-broker/src/storage/schema.rs

Complete CRUD test (MQTT & placement center) for schema

test: update schema test cases

---

src/cli-command/src/mqtt.rs

- update list_connectors method std output like list_slow_subscribe method using prettytable.
- closes https://github.com/robustmq/robustmq/issues/880
- in #906 I updated `list_connections` rather than `list_connectors` so i change `list_connectors` in this PR.
You can refer to the [GitHub Contribution …

refactor: refactor the list_connections method.

---

Cargo.lock
Cargo.toml
src/common/metadata-struct/src/mqtt/bridge/config_kafka.rs
src/grpc-clients/tests/mqtt/mqtt_admin_test.rs
src/grpc-clients/tests/placement/mqtt/mqtt_connector_test.rs
src/mqtt-broker/Cargo.toml
src/mqtt-broker/src/bridge/kafka/mod.rs
src/mqtt-broker/src/handler/error.rs

Now we can use Kafka as connector type.

feat: connector now supports Kafka plugin

---

scripts/unit-test.sh
src/storage-adapter/src/placement/mod.rs

Now we can run placement storage adapter tests :-)

fix: fixed placement storage adapter test

---

docs/zh/ContributionGuide/GitHub-Contribution-Guide.md
docs/zh/ContributionGuide/Pull-Request-Example.md

* docs: Update `GitHub-Contribution-Guide.md`
* docs: Update `Pull-Request-Example.md`
Optimize document readability and fix typos

docs: Update Constribution Guide docs in Chinese

---

src/cmd/tests/mod.rs
src/common/base/src/config/broker_mqtt.rs
src/common/base/src/config/journal_server.rs
src/common/base/src/config/placement_center.rs
src/common/base/src/error/common.rs
src/common/base/src/http_error.rs
src/common/base/src/runtime.rs
src/common/base/src/version/logo.rs
src/common/base/tests/mod.rs
src/placement-center/src/storage/mod.rs

Cleanup duplicate copyrights in the file

style: Remove duplicate copyrights in multiple files

---

docs/en/QuickGuide/mqtt/Build.md
docs/zh/QuickGuide/mqtt/Build.md

- Keep in sync with Makefile
#949

docs: Update MQTT build documentation for multiple platforms

---

README.md

* Update build & packaging link
* Enhance the introduction section with additional context.
* Add missing line breaks for better readability.
* Update URLs to use HTTPS for security.
* Improve the structure of the documentation for better navigation.
You can refer to the [GitHub Contribution …

docs: Update README.md for clarity and links

---

src/storage-adapter/src/placement/mod.rs

close #963 
implement `list_shard` for placement storage adapter

feat: placement list shard

---

src/storage-adapter/src/rocksdb/mod.rs
src/storage-adapter/src/storage.rs

close #937 
rocksdb now supports `list_shard` operation

feat: rocksdb support list shard

---

src/storage-adapter/src/rocksdb/mod.rs

close #938 
Check `ReadConfig::max_size` in reader methods and fixed leaky unit tests.

test: check read_config and fixed leaky tests

---

src/placement-center/src/mqtt/services/subscribe.rs
src/placement-center/src/server/grpc/service_mqtt.rs

Extract auto_subscribe function to reduce file size, that is  check set_auto_subscribe_rule, delete_auto_subscribe_rule, list_auto_subscribe_rule functions in src/placement-center/src/server/grpc/service_mqtt.rs, and then extract the functions into src/placement-center/src/mqtt/services/subscribe.rs.
close [#970](https://github.com/robustmq/robustmq/issues/970)

style:Extract auto_subscribe Function to Reduce File Size(#970)

---

src/placement-center/src/storage/mqtt/acl.rs

relate #900 
Add test for `AclStorage` under `src/placement-center/src/storage/mqtt/acl.rs`

test: add MQTT acl storage test

---

src/storage-adapter/src/mysql/mod.rs

close #967 
MySQL adapter now supports `list_shard` operation

feat: mysql list shard

---

src/placement-center/src/core/error.rs
src/placement-center/src/core/schema.rs
src/placement-center/src/server/grpc/service_inner.rs

Check whether the schema to be created already exists in create_schema_req 
close #908

fix:Check whether the schema to be created already exists in create_schema_req #908

---

Cargo.lock
config/log-config/mqtt-log4rs.yaml
scripts/mqtt-ig-test.sh
src/common/rocksdb-engine/Cargo.toml
src/common/rocksdb-engine/src/engine.rs
src/common/rocksdb-engine/src/lib.rs
src/mqtt-broker/src/handler/mqtt.rs
src/mqtt-broker/src/subscribe/exclusive_push.rs
src/mqtt-broker/src/subscribe/sub_common.rs
src/placement-center/src/mqtt/controller/session_expire.rs
tests/tests/mqtt_protocol/topic_rewrite_rule_test.rs

fix: Optimizing subscription logic

---

src/placement-center/src/storage/placement/cluster.rs

relate #900 
Add unit test for `src/placement-center/src/storage/placement/cluster.rs`

test: add placement cluster test

---

src/journal-client/src/client.rs
src/journal-client/src/error.rs
src/journal-client/src/service.rs
src/journal-server/src/core/cache.rs
src/journal-server/src/handler/command.rs
src/journal-server/src/handler/shard.rs
src/protocol/src/journal_server/codec.rs
src/protocol/src/journal_server/proto/engine.proto
src/storage-adapter/src/journal/mod.rs

close #986 
Journal server supports `list_shard`

feat: Journal server supports `list_shard`

---

src/placement-center/src/storage/placement/config.rs

Add unit test for ResourceConfigStorage under src/placement-center/src/storage/placement/config.rs
close [#990](https://github.com/robustmq/robustmq/issues/990)

test: Add unit test for ResourceConfigStorage

---

src/storage-adapter/src/mysql/mod.rs

close #814 
Delete stale ids in mysql auto increment tables

feat: Delete stale ids in mysql auto increment tables

---

src/placement-center/src/storage/journal/segment.rs

close #997 
Add unit test for `SegmentStorage`

test: add journal segment unit test

---

src/placement-center/src/storage/placement/idempotent.rs

Add unit test for IdempotentStorage under src/placement-center/src/storage/placement/idempotent.rs
close [#991](https://github.com/robustmq/robustmq/issues/991)

test: Add unit test for IdempotentStorage

---

Cargo.lock
src/journal-server/Cargo.toml
src/journal-server/src/server/grpc/server.rs
src/mqtt-broker/Cargo.toml
src/mqtt-broker/src/server/grpc/server.rs

feat: enable journal-server and broker-mtqq grpc-web

---

src/placement-center/src/storage/placement/offset.rs

Add unit test for OffsetStorage under src/placement-center/src/storage/placement/offset.rs
close [#996](https://github.com/robustmq/robustmq/issues/996)

test: Add unit test for OffsetStorage

---

src/grpc-clients/tests/placement/mqtt/mqtt_share_sub_test.rs

fix `mqtt_share_sub_test` in place-ig-test

fix: fix `mqtt_share_sub_test` in place-ig-test

---

src/placement-center/src/storage/journal/shard.rs

Add unit test for ShardStorage under src/placement-center/src/storage/journal/shard.rs
close [#1004](https://github.com/robustmq/robustmq/issues/1004)

test: Add unit test for JournalShard 2

---

src/common/rocksdb-engine/src/lib.rs
src/placement-center/src/route/mod.rs

fix recover snapshot serialization bug

fix: fix recover snapshot serialization bug

---

docs/en/Architect/Journal-Server.md

1. Fixed an incorrect English translation in the Journal Server documentation where a Chinese-English mixed text was present
- Translation fix
- None

docs: Update Journal Server documentation for clarity and consistency

---

src/placement-center/src/storage/journal/segment_meta.rs

- Add unit test for SegmentMetadataStorage under src/placement-center/src/storage/journal/segment_meta.rs
close #1003

test:Add unit test for segment_meta.rs

---

Cargo.lock
src/mqtt-broker/Cargo.toml
src/mqtt-broker/src/bridge/core.rs
src/mqtt-broker/src/bridge/file/mod.rs

Fix connector bug in `src/mqtt-broker/src/bridge/file/mod.rs`

fix: fix file connector bug

---

docs/en/RobustMQ-Command/Mqtt-Broker.md
docs/en/RobustMQ-Command/Overview.md
docs/zh/RobustMQ-Command/Mqtt-Broker.md
docs/zh/RobustMQ-Command/Overview.md

docs: fix some command-line document description

---

Cargo.lock
Cargo.toml
config/mqtt-server.toml
deny.toml
src/common/base/src/config/broker_mqtt.rs
src/common/base/src/config/common.rs
src/common/pprof-monitor/Cargo.toml
src/common/pprof-monitor/src/lib.rs
src/common/pprof-monitor/src/pprof_monitor.rs
src/mqtt-broker/Cargo.toml
src/mqtt-broker/src/lib.rs

close #1046 
- [❌ ]  I have written the necessary rustdoc comments.
- [❌ ]  I have added the necessary unit tests and integration tests.
- [❌ ]  This PR does not require documentation updates.
to submit the …

feat: Mqtt broker supports pprof

---

Cargo.lock
docs/.vitepress/src/sidebars/en.mts
docs/.vitepress/src/sidebars/zh.mts
docs/en/ContributionGuide/ContributingCode/Build-Develop-Env.md
docs/zh/ContributionGuide/ContributingCode/Build-Develop-Env.md

Update the Mac development environment setup guide.
no.

docs: Update the Mac development environment setup guide

---

tests/tests/mqtt_protocol/blacklist_test.rs
tests/tests/mqtt_protocol/mod.rs
tests/tests/mqtt_protocol/sub_auto.rs

test: Add autosubscribed test cases

---

Cargo.lock
Cargo.toml
src/message-expire/Cargo.toml
src/message-expire/src/lib.rs
src/message-expire/tests/mod.rs
src/mqtt-broker/src/handler/content_type.rs
src/mqtt-broker/src/handler/mod.rs
src/mqtt-broker/src/handler/validator.rs
tests/tests/mqtt_protocol/common.rs
tests/tests/mqtt_protocol/content_type_test.rs
tests/tests/mqtt_protocol/mod.rs

feat: Payload Format Indicator and Content Type functionality support

---

Cargo.lock
src/common/metadata-struct/src/mqtt/cluster.rs
src/mqtt-broker/src/handler/cluster_config.rs
src/mqtt-broker/src/handler/error.rs
src/mqtt-broker/src/handler/mqtt.rs
src/mqtt-broker/src/handler/validator.rs
src/mqtt-broker/src/subscribe/share_leader_push.rs
src/schema-register/src/avro.rs
src/schema-register/src/schema.rs
tests/Cargo.toml
tests/tests/mqtt_protocol/common.rs
tests/tests/mqtt_protocol/connect_packet_size_test.rs
tests/tests/mqtt_protocol/mod.rs
tests/tests/mqtt_protocol/schema_test.rs

test: Add integration tests for json and avro in schema

---

src/placement-center/src/storage/mqtt/blacklist.rs

Add unit test for MqttBlackListStorage under src/placement-center/src/storage/mqtt/blacklist.rs.
close #978

test: Add unit test for MqttBlackListStorage

---

docs/.vitepress/src/sidebars/zh.mts
docs/zh/Architect/Overview.md
docs/zh/QuickGuide/mqtt/FirstTask.md

1.Added a subpage called "First Task" to allow new users to get started more intuitively after installing/starting RobustMQ
2.Fixed typos in Architect/Overview.md
Related issues: #1072

docs: adding the first task document

---

src/placement-center/src/mqtt/services/session.rs
src/placement-center/src/server/grpc/service_mqtt.rs

refactor: refactor session

---

docs/.vitepress/src/sidebars/en.mts

docs: fix typo

---

LICENSE

chore: Update root's license

---

Cargo.lock
Cargo.toml
src/cli-command/src/mqtt.rs
src/common/metadata-struct/src/acl/mqtt_blacklist.rs
src/grpc-clients/tests/mqtt/mqtt_admin_test.rs
src/mqtt-broker/src/admin/acl.rs
src/mqtt-broker/src/admin/blacklist.rs
src/mqtt-broker/src/admin/client.rs
src/mqtt-broker/src/admin/mod.rs
src/mqtt-broker/src/admin/query.rs
src/mqtt-broker/src/admin/session.rs
src/mqtt-broker/src/admin/user.rs
src/mqtt-broker/src/server/grpc/admin.rs
tests/tests/mqtt_protocol/acl_test.rs
tests/tests/mqtt_protocol/blacklist_test.rs

- Add user and blacklist query list support for copilot.
- Found some bug in pagination, sort, filter query logic. Fixed in this PR.
no.

feat: add user and blacklist query list query support 

---

Cargo.lock
Cargo.toml
config/mqtt-server.toml
docs/en/Architect/Configuration/Mqtt-Server.md
docs/zh/Architect/Configuration/Mqtt-Server.md
src/common/base/Cargo.toml
src/common/base/src/config/broker_mqtt.rs
src/common/base/src/config/common.rs
src/common/base/src/config/default_mqtt.rs
src/mqtt-broker/Cargo.toml
src/mqtt-broker/src/handler/heartbreat.rs
src/mqtt-broker/src/lib.rs

feat: add heartbeat detection timeout configuration for mqtt-broker

---

src/placement-center/src/mqtt/services/acl.rs
src/placement-center/src/mqtt/services/connector.rs
src/placement-center/src/mqtt/services/share_sub.rs
src/placement-center/src/mqtt/services/subscribe.rs
src/placement-center/src/mqtt/services/topic.rs
src/placement-center/src/server/grpc/service_mqtt.rs

refactor: refactor service_mqtt in PC

---

Cargo.lock
src/placement-center/src/core/cluster.rs
src/placement-center/src/inner/mod.rs
src/placement-center/src/inner/services.rs
src/placement-center/src/lib.rs
src/placement-center/src/server/grpc/service_inner.rs

refactor: add request validate and refactor serivice_inner in PC

---

Cargo.lock
Cargo.toml
config/mqtt-server.toml
deny.toml
rust-toolchain.toml
src/cli-command/src/lib.rs
src/common/base/src/config/broker_mqtt.rs
src/common/base/src/lib.rs
src/common/metadata-struct/src/lib.rs
src/common/rocksdb-engine/src/lib.rs
src/common/third-driver/src/lib.rs
src/delay-message/src/lib.rs
src/journal-client/src/lib.rs
src/journal-server/src/lib.rs
src/journal-server/src/server/tcp/tls_server.rs
src/mqtt-broker/src/handler/mqtt.rs
src/mqtt-broker/src/lib.rs
src/mqtt-broker/src/server/tcp/tls_server.rs
src/placement-center/src/lib.rs
src/schema-register/src/lib.rs
src/storage-adapter/src/lib.rs
tests/tests/mqtt_protocol/common.rs
tests/tests/mqtt_protocol/sub_options_test.rs

feat: Isolate different tokio Runtimes in the mqtt server

---

src/placement-center/src/core/metrics.rs
src/placement-center/src/raft/store/log_store.rs
src/placement-center/src/raft/store/state_machine_store.rs

Add relevant indicators for rocksDB in the pc component:
* rocksdb.storage.num
* rocksdb.storage.error.num
* rocksdb.storage.total.ms
Considering that rocksDB is the underlying storage dependency of `StateMachine` and `LogStore` in raft, fine-grained metric recording is required.
The final effect can be seen in:
```shell
$ curl http://<placement-center>:9090/metrics
rocksdb.storage.num_total{resource_type="log",action="get"} 75
rocksdb.storage.num_total{resource_type="log",action="flush"} 71
rocksdb.storage.num_total{resource_type="log",action="set"} 141
rocksdb.storage.num_total{resource_type="snapshot",action="get"} 2
rocksdb.storage.total.ms_sum{resource_type="log",action="flush"} 2.0
rocksdb.storage.total.ms_count{resource_type="log",action="flush"} 71 …
```

feat: add rocksDB metrics in pc

---

src/common/base/src/config/broker_mqtt.rs

Fix unstable unit tests in mqtt

test: fix broker_mqtt unit test in config

---

Cargo.lock
Cargo.toml
src/cli-command/src/mqtt.rs
src/cmd/src/cli-command/command.rs
src/cmd/src/cli-command/mqtt/admin.rs
src/cmd/src/placement-center/server.rs
src/grpc-clients/src/mqtt/admin/call.rs
src/grpc-clients/src/mqtt/admin/mod.rs
src/mqtt-broker/src/admin/mod.rs
src/mqtt-broker/src/server/grpc/admin.rs
src/mqtt-broker/src/server/grpc/server.rs
src/mqtt-broker/src/subscribe/manager.rs
tests/tests/mqtt_protocol/common.rs
tests/tests/mqtt_protocol/mod.rs
tests/tests/mqtt_protocol/session_expire.rs

feat: Introduce the tokio console debugging tool

---

src/cli-command/src/mqtt.rs
src/cmd/src/cli-command/command.rs
src/cmd/src/cli-command/mqtt/admin.rs
src/common/base/src/config/broker_mqtt.rs
src/common/base/src/config/default_mqtt.rs
src/common/metadata-struct/src/mqtt/cluster.rs
src/mqtt-broker/src/handler/cluster_config.rs
src/mqtt-broker/src/handler/keep_alive.rs
src/mqtt-broker/src/handler/session.rs
src/mqtt-broker/src/server/grpc/admin.rs
src/mqtt-broker/src/server/grpc/inner.rs
tests/tests/mqtt_protocol/common.rs
tests/tests/mqtt_protocol/connect5_test.rs
tests/tests/mqtt_protocol/lastwill_message_test.rs
tests/tests/mqtt_protocol/session_expire.rs

refactor: Fix the issue of failed test cases

---

config/log-config/mqtt-tracing.toml
src/cmd/src/cli-command/command.rs
src/cmd/src/cli-command/mqtt/admin.rs
src/grpc-clients/src/pool.rs
src/mqtt-broker/src/handler/error.rs
src/mqtt-broker/src/server/connection_manager.rs
src/mqtt-broker/src/subscribe/exclusive/mod.rs

fix: Fixed the issue where the MQTT test case failed on the second run

---

docs/.vitepress/src/sidebars/en.mts
docs/.vitepress/src/sidebars/zh.mts

This PR fixes missing nav to the troubleshooting page on the sidebar.
n/a
#1129

docs: Fix link to troubleshooting page

---

example/single-mqtt-cluster/journal-server/journal-tracing.toml
example/single-mqtt-cluster/mqtt-server/mqtt-tracing.toml
example/single-mqtt-cluster/placement-center/place-tracing.toml

fix log config change configuration

chore: fix log config change configuration

---

src/mqtt-broker/src/observability/metrics/server.rs
src/mqtt-broker/src/server/packet.rs
src/mqtt-broker/src/server/quic/handler.rs
src/mqtt-broker/src/server/quic/response.rs
src/mqtt-broker/src/server/tcp/handler.rs
src/mqtt-broker/src/server/tcp/response.rs
src/mqtt-broker/src/server/websocket/server.rs
src/mqtt-broker/src/subscribe/push.rs

add time consumption metrics for `mqtt-broker`:
* request.total.ms
* request.queue.ms
* request.handler.ms
* request.response.ms
Example:
```plain text
request.response.ms_sum{network="tcp"} 1.0
request.response.ms_count{network="tcp"} 4
request.response.ms_bucket{le="5.0",network="tcp"} 4
request.response.ms_bucket{le="10.0",network="tcp"} 4
request.response.ms_bucket{le="20.0",network="tcp"} 4
request.response.ms_bucket{le="40.0",network="tcp"} 4
request.response.ms_bucket{le="80.0",network="tcp"} 4
request.response.ms_bucket{le="160.0",network="tcp"} 4
request.response.ms_bucket{le="320.0",network="tcp"} 4
request.response.ms_bucket{le="640.0",network="tcp"} 4
request.response.ms_bucket{le="1280.0",network="tcp"} 4
request.response.ms_bucket{le="2560.0",network="tcp"} 4 …
```

feat: add time consumption metrics for mqtt-broker

---

.github/workflows/unit-test.yml

add cargo expand tool for unit test workflow

chore: add cargo expand tool for unit test workflow

---

.gitignore
Cargo.lock
Cargo.toml
config/mqtt-server.toml
src/common/base/src/config/broker_mqtt.rs
src/mqtt-broker/src/handler/cache.rs
src/mqtt-broker/src/handler/lastwill.rs
src/mqtt-broker/src/handler/mqtt.rs
src/mqtt-broker/src/handler/retain.rs
src/mqtt-broker/src/server/tcp/server.rs
src/mqtt-broker/src/subscribe/common.rs
src/mqtt-broker/src/subscribe/push.rs
src/mqtt-broker/src/subscribe/share/follower.rs
tests/tests/mqtt_protocol/sub_wildcards_test.rs

fix:  Optimize the logic of kernel stability

---

Cargo.lock
Cargo.toml
src/placement-center/src/server/grpc/service_mqtt.rs
tests/tests/place_server/grpc_clients_test.rs

fix grpc client test in placement server
ref: [pr](https://github.com/robustmq/robustmq-proto/pull/19)

test: fix grpc client test in placement server

---

config/mqtt-server.toml
src/mqtt-broker/src/observability/metrics/server.rs
src/mqtt-broker/src/server/connection.rs
src/mqtt-broker/src/server/metric.rs
src/mqtt-broker/src/server/quic/response.rs
src/mqtt-broker/src/server/tcp/handler.rs
src/mqtt-broker/src/server/tcp/response.rs
src/mqtt-broker/src/server/tcp/tcp_server.rs

fix: Fix the tcp connection bug

---

README.md

Change project README.md to improve readability.

docs: Improve readme readability

---

src/mqtt-broker/src/handler/mqtt.rs
src/mqtt-broker/src/handler/subscribe.rs
src/mqtt-broker/src/handler/unsubscribe.rs
src/mqtt-broker/src/server/tcp/v1/server.rs
src/mqtt-broker/src/subscribe/common.rs
src/mqtt-broker/src/subscribe/manager.rs
src/mqtt-broker/src/subscribe/share/leader.rs
tests/tests/mqtt_protocol/common.rs
tests/tests/mqtt_protocol/mod.rs
tests/tests/mqtt_protocol/share_sub_test.rs
tests/tests/mqtt_protocol/topic_alias_test.rs

fix: bug fix for shared subscription code

---

src/cli-bench/src/kv/mod.rs
src/cli-bench/src/kv/set.rs

relate #1070 
CLI bench tool now supports KV bench set.

feat: cli-bench supports kv bench set

---

src/journal-server/src/index/build.rs
src/mqtt-broker/src/lib.rs
src/mqtt-broker/src/observability/system_topic/mod.rs
src/mqtt-broker/src/observability/system_topic/sysmon.rs

fix: Optimize and fix the bugs in the smooth exit program

---

Cargo.lock
Cargo.toml

fix: Fix the cargo dependency error

---

Cargo.lock
Cargo.toml
example/mqtt-cluster/mqtt-server/log/mqtt-tracing-1.toml
example/mqtt-cluster/mqtt-server/log/mqtt-tracing-2.toml
example/mqtt-cluster/mqtt-server/log/mqtt-tracing-3.toml
example/mqtt-cluster/mqtt-server/node-1.toml
example/mqtt-cluster/mqtt-server/node-2.toml
example/mqtt-cluster/mqtt-server/node-3.toml
src/common/metadata-struct/src/mqtt/subscribe_data.rs
src/mqtt-broker/src/handler/dynamic_cache.rs
src/mqtt-broker/src/handler/heartbreat.rs
src/mqtt-broker/src/handler/subscribe.rs
src/mqtt-broker/src/handler/unsubscribe.rs
src/mqtt-broker/src/inner/services.rs
src/mqtt-broker/src/lib.rs
src/mqtt-broker/src/server/tcp/v1/channel.rs
src/mqtt-broker/src/server/tcp/v1/common.rs
src/mqtt-broker/src/server/tcp/v1/handler.rs
src/mqtt-broker/src/server/tcp/v1/response.rs
src/mqtt-broker/src/server/tcp/v1/server.rs
src/mqtt-broker/src/subscribe/common.rs
src/mqtt-broker/src/subscribe/exclusive/mod.rs
src/mqtt-broker/src/subscribe/manager.rs
src/mqtt-broker/src/subscribe/share/follower.rs
src/mqtt-broker/src/subscribe/share/leader.rs
src/placement-center/src/core/heartbeat.rs
src/placement-center/src/mqtt/controller/call_broker.rs

refactor: Optimize the running logic of the subscription thread

---

config/log-config/mqtt-tracing.toml
src/cli-command/src/mqtt.rs
src/mqtt-broker/src/common/metrics_cache.rs
src/mqtt-broker/src/common/tool.rs
src/mqtt-broker/src/server/connection_manager.rs
src/mqtt-broker/src/server/tcp/v1/common.rs
src/mqtt-broker/src/subscribe/share/follower.rs
src/placement-center/src/core/cache.rs
src/placement-center/src/core/cluster.rs
src/placement-center/src/core/heartbeat.rs

fix: Add the command line "status" to display data

---

src/mqtt-broker/src/admin/acl.rs
src/mqtt-broker/src/admin/blacklist.rs
src/mqtt-broker/src/admin/client.rs
src/mqtt-broker/src/admin/cluster.rs
src/mqtt-broker/src/admin/connector.rs
src/mqtt-broker/src/admin/mod.rs
src/mqtt-broker/src/admin/observability.rs
src/mqtt-broker/src/admin/schema.rs
src/mqtt-broker/src/admin/session.rs
src/mqtt-broker/src/admin/subscribe.rs
src/mqtt-broker/src/admin/topic.rs
src/mqtt-broker/src/admin/user.rs
src/mqtt-broker/src/server/grpc/admin.rs

refactor: refactor amin.rs in mqtt-broker

---

README.md

docs: add ask deepwiki

---

src/grpc-clients/tests/placement/mqtt/cluster_test.rs
src/journal-server/src/admin/mod.rs
src/journal-server/src/admin/services.rs
src/journal-server/src/inner/mod.rs
src/journal-server/src/inner/services.rs
src/journal-server/src/lib.rs
src/journal-server/src/server/grpc/admin.rs
src/journal-server/src/server/grpc/inner.rs
src/mqtt-broker/src/admin/mod.rs

refactor: refactor journal server grpc interface function

---

src/common/base/src/utils/mod.rs
src/common/base/src/utils/time_util.rs
src/common/metadata-struct/src/placement/node.rs
src/mqtt-broker/src/storage/session.rs

style: simplified code

---

Cargo.lock
src/common/rocksdb-engine/src/engine.rs
src/placement-center/src/core/metrics.rs
src/placement-center/src/mqtt/services/topic.rs
src/placement-center/src/storage/mqtt/metrics.rs
src/placement-center/src/storage/mqtt/topic.rs

feat: add topic num metrics

---

Cargo.lock
Cargo.toml
src/common/base/Cargo.toml
src/common/base/src/utils/time_util.rs

feat: Improve the time tool class. test does not perform assert judgmentsDevelop

---

Cargo.lock
Cargo.toml
src/cli-command/src/mqtt.rs
src/cmd/src/cli-command/command.rs
src/cmd/src/cli-command/mqtt/admin.rs
src/common/metadata-struct/src/mqtt/subscribe_data.rs
src/grpc-clients/src/mqtt/admin/call.rs
src/grpc-clients/src/mqtt/admin/mod.rs
src/mqtt-broker/src/admin/subscribe.rs
src/mqtt-broker/src/handler/subscribe.rs
src/mqtt-broker/src/handler/unsubscribe.rs
src/mqtt-broker/src/server/grpc/admin.rs
src/mqtt-broker/src/subscribe/common.rs
src/mqtt-broker/src/subscribe/manager.rs

feat: Add interface related to subscription list

---

.github/workflows/code-style.yml
codecheck.sh
rust-toolchain.toml

chore: replace toolchain with the tracked stable version

chore: replace toolchain with the tracked stable version

---

Cargo.lock
src/grpc-clients/src/placement/mqtt/call.rs
src/grpc-clients/src/placement/mqtt/mod.rs
src/placement-center/src/mqtt/services/topic.rs
src/placement-center/src/server/grpc/service_mqtt.rs

feat: add interface about geting retain message

---

src/mqtt-broker/src/security/auth/blacklist.rs
src/mqtt-broker/src/security/auth/mod.rs
src/mqtt-broker/src/security/mod.rs

This PR handles multiple things:
1.  hardens the security module by replacing .unwrap() calls with robust error handling to prevent panics during authorization checks. This ensures that if a check fails, we default to a "fail-safe" state instead of crashing
2.
3.
4.
relate #1278

refactor: Security module code optimization

---

src/cmd/src/cli-command/mqtt/admin.rs

style: Resolve style inconsistencies in the command-line interface

---

src/cmd/src/cli-command/command.rs
src/cmd/src/cli-command/mqtt/admin.rs

style:fix schema style

---

src/mqtt-broker/src/subscribe/share/follower.rs

refactor: Reduce excessive function parameters in follower.rs

---

src/mqtt-broker/src/server/tcp/v1/tcp_acceptor.rs

In the original `fn acceptor_process` processing logic, a new connection is accepted, and a `NetworkConnection` data structure is created, and then `fn read_frame_process` is further called for processing.
There is a problem at this time: `fn read_frame_process` continuously polls the socket stream to obtain new requests on the same connection. Then the connection used in the entire function scope is not the same as the one managed in connection_manager! So we fix this

fix: fixing inconsistent connections

---

Cargo.lock
Cargo.toml
src/common/metadata-struct/src/mqtt/bridge/config_greptimedb.rs
src/common/metadata-struct/src/mqtt/bridge/connector.rs
src/common/metadata-struct/src/mqtt/bridge/connector_type.rs
src/common/metadata-struct/src/mqtt/bridge/mod.rs
src/mqtt-broker/Cargo.toml
src/mqtt-broker/src/admin/connector.rs
src/mqtt-broker/src/bridge/core.rs
src/mqtt-broker/src/bridge/greptimedb/mod.rs
src/mqtt-broker/src/bridge/greptimedb/sender.rs
src/mqtt-broker/src/bridge/mod.rs
src/mqtt-broker/src/handler/error.rs

Support sending MQTT record to GreptimeDB via line protocal.
This is the result of sending data to GreptimeDB 
As the result shows, the record.Head is treated as line protocal `tags`, record.data\record.tags\record.crc_num  is treated as `fields`.
Close https://github.com/robustmq/robustmq/issues/1240

feat: Add GreptimeDB connector for MQTT.

---

src/mqtt-broker/src/handler/cache.rs

Add test cases to the method of the file: src/mqtt-broker/src/handler/cache.rs
close #1216

test: Add test cases to the method of cache.rs

---

src/mqtt-broker/src/bridge/core.rs
src/mqtt-broker/src/bridge/greptimedb/sender.rs
src/mqtt-broker/src/bridge/heartbeat.rs
src/mqtt-broker/src/bridge/manager.rs

Add test cases for the MQTT Bridge module and fix GreptimeDB sender tags field
close #1218

test: Add test cases for the MQTT Bridge module 

---

docs/en/ContributionGuide/ContributingDoc/Doc-Contribution-Guide.md
docs/en/QuickGuide/mqtt/First-Task.md
docs/zh/ContributionGuide/ContributingDoc/Doc-Contribution-Guide.md
docs/zh/QuickGuide/mqtt/First-Task.md

fix: Fix the error in the document address.

---

docs/.vitepress/src/sidebars/en.mts
docs/.vitepress/src/sidebars/zh.mts
docs/en/Blogs/01.md
docs/en/RobustMQ-MQTT/MQTTX-Guide.md
docs/en/RobustMQ-MQTT/SDK/c-sdk.md
docs/en/RobustMQ-MQTT/SDK/go-sdk.md
docs/en/RobustMQ-MQTT/SDK/java-sdk.md
docs/en/RobustMQ-MQTT/SDK/javascript-sdk.md
docs/en/RobustMQ-MQTT/SDK/python-sdk.md
docs/zh/Blogs/01.md
docs/zh/RobustMQ-MQTT/MQTTX-Guide.md
docs/zh/RobustMQ-MQTT/Overview.md
docs/zh/RobustMQ-MQTT/SDK/c-sdk.md
docs/zh/RobustMQ-MQTT/SDK/go-sdk.md
docs/zh/RobustMQ-MQTT/SDK/java-sdk.md
docs/zh/RobustMQ-MQTT/SDK/javascript-sdk.md
docs/zh/RobustMQ-MQTT/SDK/python-sdk.md

docs: Improve the documentation of the MQTT broker

---

docs/en/OverView/SignYourName.md
docs/zh/OverView/SignYourName.md

docs: @Ayanokoji-li Nice to meet you

---

docs/en/OverView/SignYourName.md
docs/zh/OverView/SignYourName.md

relate [#1380](https://github.com/robustmq/robustmq/issues/1380)

docs: @patwrall Nice to meet you

---

docs/en/OverView/SignYourName.md
docs/zh/OverView/SignYourName.md

docs: @flyswimmer Nice to meet you (#1384)

---

docs/en/OverView/SignYourName.md
docs/zh/OverView/SignYourName.md

‘relate https://github.com/robustmq/robustmq/issues/1380’

docs: @satori1995 Nice to meet you

---

docs/en/OverView/SignYourName.md
docs/zh/OverView/SignYourName.md

- docs: @NuclEnergy Nice to meet you
- style: Formatting some docs

docs: @NuclEnergy Nice to meet you

---

docs/en/OverView/SignYourName.md
docs/zh/OverView/SignYourName.md

Nice to meet you!
relate #1380

docs: @WaterWhisperer Nice to meet you

---

docs/en/OverView/SignYourName.md
docs/zh/OverView/SignYourName.md

docs: @hzbnb Nice to meet you

---

docs/en/OverView/SignYourName.md
docs/zh/OverView/SignYourName.md

chore: sign myself

---

docs/en/OverView/SignYourName.md
docs/zh/OverView/SignYourName.md

Nice to meet you !
relate #1380

docs: @chenxi2015 Nice to meet you

---

docs/zh/OverView/SignYourName.md

docs: @yqingyu Nice to meet you

---

docs/en/OverView/SignYourName.md
docs/zh/OverView/SignYourName.md

relate https://github.com/robustmq/robustmq/issues/1380

docs: @codenohup Nice to meet you

---

docs/en/OverView/SignYourName.md
docs/zh/OverView/SignYourName.md

docs: @dwsio Nice to meet you

---

Cargo.toml
src/common/base/Cargo.toml
src/robustmq-macro/Cargo.toml
tests/Cargo.toml

https://github.com/mainmatter/cargo-autoinherit is tools that can de-duplicate the depencies that used in multiplicate place, 
it's recommend that specify the version in the workspace mainifest and the sub crates inherit fromt it.

chore: use `cargo-autoinherit` to de-duplicate the dependices.

---

docker/Dockerfile

Fix the Dockerfile to make it build successfully and run normally
the image can be successfully created
the image can run normally
close #1412

fix: Fix the Dockerfile to make it build and run normally

---

docs/.vitepress/config.mts
docs/.vitepress/src/configs/en.mts
docs/.vitepress/src/configs/zh.mts
docs/.vitepress/src/nav/en.mts
docs/.vitepress/src/sidebars/en.mts
docs/.vitepress/src/sidebars/zh.mts
docs/OverView/Diff-MQ.md
docs/OverView/Diff-iggy.md
docs/OverView/What-is-RobustMQ.md
docs/OverView/Why-RobustMQ.md
docs/OverView/index.md
docs/en/RobustMQ-MQTT/Bridge/GreptimeDB.md
docs/en/RobustMQ-MQTT/Bridge/Kafka.md
docs/en/RobustMQ-MQTT/Bridge/LocalFile.md
docs/en/RobustMQ-MQTT/Bridge/Overview.md
docs/en/index.md
docs/index.md
docs/zh/RobustMQ-MQTT/Bridge/GreptimeDB.md
docs/zh/RobustMQ-MQTT/Bridge/Kafka.md
docs/zh/RobustMQ-MQTT/Bridge/LocalFile.md
docs/zh/RobustMQ-MQTT/Bridge/Overview.md
docs/zh/index.md

docs: Improve the MQTT connector documentation

---

docs/.vitepress/config.mts
docs/index.md

fix: Fix the issue of disordered styles in the front-end page. 

---

docs/en/Observability/Grafana-Configuration-Guide.md
docs/en/Observability/Prometheus-Integration.md
docs/zh/Observability/Grafana配置指南.md
docs/zh/Observability/MQTT专用指标.md
docs/zh/Observability/Prometheus接入.md
docs/zh/Observability/基础设施指标.md

fix: Fix the bugs in the document

---

src/common/metadata-struct/src/mqtt/bridge/config_postgres.rs
src/mqtt-broker/src/bridge/postgres/mod.rs

Add batch insert and upsert support for postgres bridge.
#1230

feat: add batch insert and upsert support for postgres bridge

---

docs/en/OverView/SignYourName.md
docs/zh/OverView/SignYourName.md

docs: @reigadegr Nice to meet you

---

Cargo.lock
Cargo.toml
deny.toml
src/admin-server/src/mqtt/connector.rs
src/common/metadata-struct/src/mqtt/bridge/config_mongodb.rs
src/common/metadata-struct/src/mqtt/bridge/connector_type.rs
src/common/metadata-struct/src/mqtt/bridge/mod.rs
src/mqtt-broker/Cargo.toml
src/mqtt-broker/src/bridge/core.rs
src/mqtt-broker/src/bridge/mod.rs
src/mqtt-broker/src/bridge/mongodb/mod.rs
src/mqtt-broker/src/handler/error.rs

MQTT proxy supports sending data to MongoDB.
#1229

feat: Add `MongoDB` connector.

---

Cargo.lock
Cargo.toml
src/admin-server/src/mqtt/connector.rs
src/common/metadata-struct/src/mqtt/bridge/config_rabbitmq.rs
src/common/metadata-struct/src/mqtt/bridge/connector_type.rs
src/common/metadata-struct/src/mqtt/bridge/mod.rs
src/mqtt-broker/Cargo.toml
src/mqtt-broker/src/bridge/core.rs
src/mqtt-broker/src/bridge/mod.rs
src/mqtt-broker/src/bridge/rabbitmq/mod.rs
src/mqtt-broker/src/handler/error.rs

MQTT proxy supports sending data to RabbitMQ.
#1225

feat: Add `RabbitMQ` connector.

---

src/admin-server/src/mqtt/topic.rs
src/meta-service/src/controller/mqtt/mod.rs
src/mqtt-broker/src/handler/cache.rs
src/mqtt-broker/src/handler/topic.rs
src/mqtt-broker/src/handler/topic_rewrite.rs
tests/tests/mqtt/protocol/acl_test.rs
tests/tests/mqtt/protocol/blacklist_test.rs
tests/tests/mqtt/protocol/common.rs
tests/tests/mqtt/protocol/flapping_detect_test.rs
tests/tests/mqtt/protocol/schema_test.rs
tests/tests/mqtt/protocol/session_expire.rs
tests/tests/mqtt/protocol/sub_auto.rs
tests/tests/mqtt/protocol/sub_identifier_test.rs
tests/tests/mqtt/protocol/topic_rewrite_test.rs
tests/tests/mqtt/protocol/user_test.rs

refactor: Optimize performance && Fix the failure of unit tests
