robustmq/robustmq

src/journal-server/src/record/header.rs, src/journal-server/src/server/tcp/connection.rs, src/journal-server/src/storage.rs, src/mqtt-broker/src/observability/slow/qos.rs, src/mqtt-broker/tests/share_sub_test.rs, src/placement-center/src/core/share_sub.rs, src/placement-center/src/raft/metadata.rs, src/placement-center/src/server/http/server.rs, src/placement-center/src/storage/journal/segment.rs, src/placement-center/src/storage/rocksdb.rs, src/protocol/tests/mqtt_frame.rs
_Fixed all the warning message for unused code_
- Removed the warning message in compilation.
- Update your code and rebuild the poject, warning messages should be disappeared.
- #[allow(dead_code)] added for unused code.
- It is better to remove this kind of unused code rather than tag it with #[allow(dead_code)].
close  #442
=> fix: warning message for unused code

README.md, docs/cn/系统架构/概览.md
Fix typos in documentation: "Plagement" to "Placement" , "Apache Bookeeper" to "Apache BookKeeper" in README.md , 概览.md
=> docs: Fix typos in documentation

src/journal-server/src/server/connection.rs, src/journal-server/src/server/connection_manager.rs, src/journal-server/src/server/tcp/server.rs, src/journal-server/src/server/tcp/tls_server.rs, src/mqtt-broker/src/server/connection.rs, src/mqtt-broker/src/server/connection_manager.rs, src/mqtt-broker/src/server/tcp/server.rs, src/mqtt-broker/src/server/tcp/tls_server.rs, src/protocol/src/mqtt/mqttv4/connect.rs, src/protocol/tests/mqtt_frame.rs
Renamed `NetworkConnectionType::Tcps` to `NetworkConnectionType::Tls`. Tls is much more accepted in the rust community, and it's very rare to see anyone using Tcps to described a secured TCP connection.
- Renamed `NetworkConnectionType::Tcps` to `NetworkConnectionType::Tls`.
- Remove `assert!(true)` and replace `assert!(false)` with `panic!(...)`
=> chore: renamed Tcps to Tls

src/grpc-clients/tests/placement_test.rs, src/placement-center/src/server/grpc/service_placement.rs, src/placement-center/src/server/grpc/validate.rs
- add validation to the un_register_node method in GrpcPlacementService 
- add un_register_node test case to src/grpc-clients/tests/placement_test.rs
relate https://github.com/robustmq/robustmq/issues/539
=> refactor: add validation to the un_register_node method in GrpcPlacementService and fill in the test case

src/common/base/src/config/broker_mqtt.rs, src/common/base/src/config/default_mqtt.rs, src/common/base/src/config/journal_server.rs, src/journal-server/src/lib.rs, src/journal-server/src/server/grpc/server.rs, src/journal-server/src/server/tcp/server.rs, src/mqtt-broker/src/server/tcp/server.rs, src/mqtt-broker/src/storage/cluster.rs
This PR adds TLS support for gRPC servers in mqtt-broker, journal server and placement center
- Adds `grpc_tls_enable: bool` option to network config of `JournalServerConfig`
- The gRPC server serves with TLS enabled if `grpc_tls_enable` is found to be `true`
#521
=> feat: Add TLS support for gRPC servers

src/common/base/src/config/broker_mqtt.rs, src/common/base/src/config/default_mqtt.rs, src/common/base/src/config/journal_server.rs, src/journal-server/src/lib.rs, src/journal-server/src/server/grpc/server.rs, src/journal-server/src/server/tcp/server.rs, src/mqtt-broker/src/server/tcp/server.rs, src/mqtt-broker/src/storage/cluster.rs
Reverts robustmq/robustmq#579
#579 was not complete when it was merged
=> fix: Revert "feat: Add TLS support for gRPC servers"

.github/actions/setup-builder/action.yaml, .github/actions/setup-rust-runtime/action.yml, .github/workflows/rust-testing.yml, scripts/integration-testing.sh
By referring to [Apache Datafusion](https://github.com/apache/datafusion), we have modified our CI/CD pipeline to implement caching of compilation files through sccache, which has reduced the compilation time in CI/CD.
There is not a related PR.
=> ci: Implement caching for CI/CD builds using sccache.

src/placement-center/src/lib.rs, src/placement-center/src/raft/raft_node.rs
- Delete invalid prefixes in lib.rs
=> fix: Remove code that initializes the cache repeatedly

src/placement-center/src/core/cluster.rs
- Update node id validation to ensure it's within the range of 1 to 65536- Change panic message to accurately reflect the valid range
=> fix: correct node id range check

src/placement-center/src/core/cache.rs, src/placement-center/src/core/cluster.rs, src/placement-center/src/core/controller.rs
- Remove placement_cluster field from PlacementCacheManager
- Delete ClusterMetadata struct and related functions
- Clean up unused imports and code related to placement cluster
=> refactor: remove unused placement cluster metadata

.gitignore, src/grpc-clients/tests/placement/mqtt/mqtt_share_sub_test.rs, src/placement-center/src/server/grpc/service_mqtt.rs, src/placement-center/src/server/grpc/validate.rs
add validation for get_share_sub_leader method
* group_name shoud not be empty
* cluster_name should not be empty
https://github.com/robustmq/robustmq/issues/541
close #541
=> feat: add validation for get_share_sub_leader method

.github/actions/build-linux-artifacts/action.yml, .github/actions/build-macos-artifacts/action.yml, .gitignore, config/journal-server.toml, config/mqtt-server.toml, config/placement-center.toml, docs/cn/系统架构/配置说明/mqtt-server.md, docs/cn/系统架构/配置说明/placement-center.md, example/mqtt-cluster/journal-server/node-1.toml, example/mqtt-cluster/mqtt-server/node-1.toml, example/mqtt-cluster/mqtt-server/node-2.toml, example/mqtt-cluster/mqtt-server/node-3.toml, example/mqtt-cluster/placement-center/node-1.toml, example/mqtt-cluster/placement-center/node-2.toml, example/mqtt-cluster/placement-center/node-3.toml, example/mqtt-cluster/stop.sh, scripts/journal-ig-test.sh, scripts/mqtt-ig-test.sh, scripts/place-ig-test.sh, src/common/base/src/config/broker_mqtt.rs, src/common/base/src/config/default_placement_center.rs, src/common/base/src/config/placement_center.rs, src/mqtt-broker/src/subscribe/sub_common.rs, src/mqtt-broker/src/subscribe/subscribe_manager.rs, tests/tests/mqtt_protocol/share_sub_test.rs, tests/tests/place_server/share_sub.rs
subscribe support queue mode
- parse_subscribe method support decode queue example like '$queue/t/1'
- reusing shared subscription logic with group set to $queue/{topic_name}
https://github.com/robustmq/robustmq/issues/550
=> feat: subscribe support queue mode

src/grpc-clients/tests/placement/mqtt/cluster_test.rs, src/placement-center/src/server/grpc/service_inner.rs, src/placement-center/src/server/grpc/validate.rs
close #546 
Add validation to `exists_idempotent_data` method (`cluster_name` and `producer_id` field should not be empty) and filled in the test case.
=> chore: Add validation to exists_idempotent_data and test

src/grpc-clients/tests/placement/mqtt/cluster_test.rs, src/placement-center/src/server/grpc/service_inner.rs, src/placement-center/src/server/grpc/validate.rs
close #544 
Add validation to the `delete_resource_config` method (`cluster_name` should not be empty) and add the corresponding test case.
=> chore: Add validation to the delete_resource_config method and test

.github/actions/setup-builder/action.yaml, .github/workflows/apidoc.yml, rust-toolchain.toml, rustfmt.toml
close #738 
It seems like all unit tests and integration tests work properly when stable toolchain is used.
=> build: Change rust toolchain version from nightly to stable

src/mqtt-broker/src/handler/connection.rs, src/mqtt-broker/src/handler/pkid.rs, src/mqtt-broker/src/handler/session.rs
close #697 
Replace all `CommonError` under `mqtt-broker` with `MqttBrokerError`
=> refactor: Replace CommonError in mqtt-broker with MqttBrokerError

Dockerfile, example/test-network-k8s/kube/cli-command.yaml, example/test-network-k8s/kube/mqtt-server.yaml, example/test-network-k8s/network.sh, example/test-network-k8s/scripts/docker.sh, example/test-network-k8s/scripts/kind.sh, example/test-network-k8s/scripts/robustmq.sh
1. cli-command image build added to Dockerfile
2. Start a cli-command in k8s to facilitate testing cluster functions in a cloud environment
2.1 Demo
```console
% kubectl exec -it cli-command-6fbf8b6cc-7ldqp -n robustmq -- /bin/sh
able to connect: "mqtt-server-cs.robustmq.svc.cluster.local:1883"
you can post a message on the terminal:
1
> You typed: 1
2 
> You typed: 2
3
> You typed: 3
^C>  Ctrl+C detected,  Please press ENTER to end the program. 
```
```console
kubectl exec -it cli-command-6fbf8b6cc-7ldqp -n robustmq -- /bin/sh
able to connect: "mqtt-server-cs.robustmq.svc.cluster.local:1883"
subscribe success
payload: 1
payload: 2
payload: 3
^C Ctrl+C detected,  Please press ENTER to end the program. 
End of input stream.
```
=> feat: add cli-command yaml to  k8s-dev

Cargo.lock, Cargo.toml, src/cli-command/src/mqtt.rs, src/journal-server/src/segment/read.rs, src/placement-center/Cargo.toml, src/placement-center/src/server/grpc/service_inner.rs, src/protocol/Cargo.toml, src/protocol/build.rs, src/protocol/src/placement_center/proto/inner.proto, src/protocol/src/prost_validation_types/proto/validate/validate.proto
Right now for every RPC we need to write a validate function manually. By using `prost-validate` we can add rules in proto files and generated code will help us with a validate method automatically. 
1. Update `tonic`, `tonic-build` to `0.12.3` from `0.11.0`
2. Update `prost` to `0.13.2` from `0.12.3` and added `prost-build`, `prost-validate` and `prost-validate-build` as new dependencies
3. Update `prost` to use workspace versions across packages instead of hardcoding
4. Update `build.rs` to replace deprecated methods with new ones
5. `validate.proto` file. Ref to [issue](https://github.com/linka-cloud/prost-validate/issues/9#issuecomment-2606537257)
6. proto file changes for `GetOffsetDataRequest` to include validations
Closes: https://github.com/robustmq/robustmq/issues/768
=> feat: add prost validations for grpc methods

src/common/base/src/config/broker_mqtt.rs, src/common/base/src/config/default_mqtt.rs, src/common/metadata-struct/src/mqtt/cluster.rs, src/mqtt-broker/src/handler/cluster_config.rs
1. New fields in local configuration
```
#[serde(default = "default_mqtt_cluster_dynamic_slow_sub")]
pub cluster_dynamic_config_slow_sub: MqttClusterDynamicSlowSub,
#[serde(default = "default_mqtt_cluster_dynamic_flapping_detect")]
pub cluster_dynamic_config_flapping_detect: MqttClusterDynamicFlappingDetect,
#[serde(default = "default_mqtt_cluster_dynamic_protocol")]
pub cluster_dynamic_config_protocol: MqttClusterDynamicConfigProtocol,
#[serde(default = "default_mqtt_cluster_dynamic_feature")]
pub cluster_dynamic_config_feature: MqttClusterDynamicConfigFeature,
#[serde(default = "default_mqtt_cluster_dynamic_security")]
pub cluster_dynamic_config_security: MqttClusterDynamicConfigSecurity,
#[serde(default = "default_mqtt_cluster_dynamic_network")]
pub cluster_dynamic_config_network: …
```
=> feat: dynamic configuration and the local static configuration are merged

src/placement-center/src/mqtt/cache.rs
Load all connectors from rocksdb to MQTTCache when the placement center starts.
=> feat: load mqtt connector to PC MQTT cache

src/mqtt-broker/src/bridge/core.rs, src/mqtt-broker/src/lib.rs
Update GC logic in `src/mqtt-broker/src/bridge/core.rs` - no need to send `update_connector` request to the placement center.
=> chore: no need to send update connector request to PC during GC

src/placement-center/src/core/schema.rs
This PR is to address issue close #909. Updated the update_schema_req() function; added a condition to check whether the schema to be updated exists. It returns an error `PlacementCenterError::SchemaNotFound` if schema is not found
You can refer to the [GitHub Contribution Guide](https://robustmq.com/ContributionGuide/GitHub-Contribut …
=> fix:  if schema to be updated exists for update_schem_req() function. close #909

Cargo.lock, Cargo.toml
- Enable the CMake-build feature of rdkafka to solve the compilation problem on Windows.
=> fix(rdkafka): Fixed Win compilation issues

example/mqtt-cluster/placement-center/node-2.toml, example/mqtt-cluster/placement-center/node-3.toml, src/placement-center/src/raft/raft_node.rs
- Remove calc_init_node function from raft_node.rs
- Update log_config path in placement center config files
- Refactor node initialization logic for better readability and efficiency
Reason:  Raft::initialize() this method is called on more than one node simultaneously with the same membership, it is safe, as the voting protocol ensures consistency.
=> refactor: remove calc_init_node function and update log config path

Cargo.lock, Cargo.toml, src/placement-center/Cargo.toml, src/placement-center/src/storage/placement/kv.rs
- Implement unit tests for KvStorage to ensure basic functionality- Add tests for set, get, delete, and exists operations
- Include tests for prefix-based retrieval
- Update dependencies to include tempfile for temporary directory creation
=> test(placement-center): add unit tests for KvStorage

Cargo.lock, scripts/build-release.sh
- Change bash-specific array syntax `binaries=()` to POSIX shell compatible string form
- Improve cross-platform compatibility of scripts to ensure that they can run properly in different shell implementations (such as dash)
- Adjust ident for the `Cargo.lock`
=> fix: Use POSIX compatible array syntax

src/placement-center/src/storage/placement/node.rs
- Implement tests for save, get, and delete operations
- Verify correct behavior for existing and non-existent nodes
- Use temporary RocksDB storage for testing
=> test(node): add unit tests for NodeStorage

src/common/metadata-struct/src/mqtt/subscribe_data.rs, src/placement-center/src/storage/mqtt/subscribe.rs, src/protocol/src/mqtt/common.rs
Add unit test for MqttSubscribeStorage under src/placement-center/src/storage/mqtt/subscribe.rs
close [#979](https://github.com/robustmq/robustmq/issues/979)
=> test: Add unit test for MqttSubscribeStorage

Cargo.lock, src/common/rocksdb-engine/Cargo.toml, src/common/rocksdb-engine/src/engine.rs
Fix resource busy bug when running multiple rocksdb instances concurrently.
=> fix: fix resource busy bug when running multiple rocksdb instances concurrently

Cargo.lock, src/cli-command/src/mqtt.rs, src/cmd/src/cli-command/command.rs, src/cmd/src/cli-command/mqtt/admin.rs, src/common/metadata-struct/src/acl/mqtt_acl.rs
- The current CLI capabilities supported by the Robustctl MQTT command line are not comprehensive enough. Every service in src/mgtt-broker/src/admin needs to have a corresponding command line tool. Therefore, it is necessary to compare the differences between the current Robustctl and the services provided by admin, and then improve the CLI.
- In this PR, I focus on acl and blacklist. The implementation of Robustctl MQTT Command now does not support them, so I decide to complete this.
- There are still many areas where the current command support is incomplete, and there is much room for optimization in the code structure and style. I plan to make more improvements and enhancements to the command module in the near future.
close [#1020](https://github.com/robustmq/robustmq/issues/1020)
=> feat: Robustctl MQTT Command support Acl and Blacklist

docs/en/RobustMQ-MQTT/TopicRewrite.md, src/mqtt-broker/src/handler/topic_rewrite.rs, src/mqtt-broker/src/subscribe/sub_common.rs
Add unit test and documents for mqtt topic rewrite.
- Add document to illustrthe the topic rewrite function.
- Fix topic filter with both "+" and "#" wildcasts.
- Rollback unstable async closure.
#837
=> test: Add unit test and documents for mqtt topic rewrite

docs/en/RobustMQ-Command/Mqtt-Broker.md, docs/zh/RobustMQ-Command/Mqtt-Broker.md, src/cli-command/src/mqtt.rs, src/mqtt-broker/src/handler/topic_rewrite.rs, src/mqtt-broker/src/subscribe/sub_common.rs
- add mqtt command doc for acl and blacklist.
- run "Cargo fmt" to format code that is introduced in a previous PR(#1022 ). This PR (https://github.com/robustmq/robustmq/pull/1022 ) was merged despite failing to pass CI.
close [#1029](https://github.com/robustmq/robustmq/issues/1029)
=> docs: add mqtt command doc for acl and blacklist

src/cli-command/src/mqtt.rs, src/cmd/src/cli-command/command.rs, src/cmd/src/cli-command/mqtt/admin.rs
- The current CLI capabilities supported by the robustctl MQTT command line are not comprehensive enough. The principle is that all services in src/mqtt-broker/src/admin need to have corresponding command line tools. Therefore, it is necessary to compare the differences between the current robustctl and the services provided by admin, and then improve the CLI.
Compare: src/cmd/src/cli-command/command.rs and https://github.com/robustmq/robustmq-proto/blob/main/protos/broker_mqtt/proto/admin.proto to obtain the information.
- First, I noticed the the existing implementation of the MQTT command related to the connector is non-standard and lacks readability.So I refectored it …
=> refactor: Refactor Connector and add Topic Rewrite support in MQTT Command 

scripts/check-place-status.sh, scripts/place-ig-test.sh
relate #1035 
Check whether the status of PC is "Running" before starting placement integration test.
=> test: check placement status before starting test

docs/.vitepress/src/configs/en.mts, docs/.vitepress/src/configs/zh.mts, docs/en/ContributionGuide/ContributingDoc/Build-Doc-Env.md, docs/zh/ContributionGuide/ContributingDoc/Build-Doc-Env.md
- Add social links to documents to quickly jump to GitHub repositories
- Build Doc Env Guide Add Windows System Installation Node.js Environment Instructions
close #1044
=> docs: add the social links and doc env guide add windows Installation nodejs

Cargo.lock, Cargo.toml, src/mqtt-broker/src/admin/client.rs, src/mqtt-broker/src/admin/mod.rs, src/mqtt-broker/src/admin/query.rs, src/mqtt-broker/src/admin/session.rs, src/mqtt-broker/src/admin/user.rs, src/mqtt-broker/src/server/grpc/admin.rs
-  Add unified query trait for pagination, sort, filter support for session and client list.
- The `Queryable` trait provides a uniform way to retrieve a named field’s string representation, enabling shared implementations of filtering, sorting, and pagination across different data types (e.g., `SessionRaw`,  `ClientRaw`, etc.). By mapping field names to `Option<String>`, each implementer can handle optional fields and custom formatting. This trait can be implement for all the fields used in the dashboard.
close #1079
=> feat: add pagination, sort, filter support for session and client list query

_typos.toml, src/mqtt-broker/src/observability/metrics/packets.rs, src/placement-center/src/raft/raft_node.rs, src/placement-center/src/raft/store/state_machine_store.rs, src/protocol/src/mqtt/mqttv5/connect.rs, src/protocol/src/mqtt/mqttv5/publish.rs
**MQTT Packet Metric Constant Typos**: 
- `PACKETS_SUBSCRIBLE_RECEIVED` → `PACKETS_SUBSCRIBE_RECEIVED` 
- `PACKETS_UNSUBSCRIBLE_RECEIVED` → `PACKETS_UNSUBSCRIBE_RECEIVED` 
**Variable/Module Naming Improvements**: 
- In MQTT v5 protocol: `typ` → `content_type_value`
- In Raft module: `mod typ` → `mod types`
**Configuration Cleanup**: 
- Updated `_typos.toml` to remove ignore rules for already-fixed typos 
close #1053
=> fix: Fix typos errors in pre-commit and _typos.toml - close #1053

config/log-config/mqtt-tracing.toml, config/log-config/place-tracing.toml
This PR fixes a mistake introduced in the prior PR #1137 where the `TokioConsole` appender entry is enabled in the default logging config files for placement center and mqtt broker. This is a problem because this appender would panic if `tokio_unstable` cfg is not enabled, and this is not the most common use case.
Comment out the `TokioConsole` entries in the two logging config files
n/a
=> fix: Disable TokioConsole entry in logging config by default

src/robustmq-macro/src/lib.rs, src/robustmq-macro/src/parse.rs, src/robustmq-macro/src/tools.rs, src/robustmq-macro/src/validate_req.rs, src/robustmq-macro/tests/expand.rs, src/robustmq-macro/tests/validate_req/expand/fn_success.expanded.rs, src/robustmq-macro/tests/validate_req/expand/fn_success.rs, src/robustmq-macro/tests/validate_req/expand/impl_success.expanded.rs, src/robustmq-macro/tests/validate_req/expand/impl_success.rs
add impl expand validate stmt for validate_req
example:
```rust
#[async_trait::async_trait]
pub trait HeyGRPC {
async fn hey(
&self,
_request: tonic::Request<Request>,
) -> Result<tonic::Response<Response>, tonic::Status>;
async fn hi(
&self,
_request: tonic::Request<Request>,
) -> Result<tonic::Response<Response>, tonic::Status>;
}
#[async_trait::async_trait]
#[robustmq_macro::validate_req(validator = prost_validate::Validator)]
impl HeyGRPC for FooService {
async fn hey(
&self,
_request: tonic::Request<Request>,
) -> Result<tonic::Response<Response>, tonic::Status> {
Ok(tonic::Response::new(Response {}))
}
async fn hi(
&self,
_request: tonic::Request<Request>,
) -> Result<tonic::Response<Response>, tonic::Status> {
Ok(tonic::Response::new(Response {}))
}
}
// …
```
=> feat: add impl expand validate stmt for validate_req

Cargo.lock, docs/zh/ContributionGuide/GitHub-Contribution-Guide.md
add sign off doc to contributor guide
=> docs: add sign off doc to contributor guide

docs/en/ContributionGuide/GitHub-Contribution-Guide.md, docs/zh/ContributionGuide/GitHub-Contribution-Guide.md
add sign off doc to contributor guide(en)
=> docs: add sign off doc to contributor guide(en)

src/journal-client/src/lib.rs, src/journal-client/src/option.rs
We use Result<(), Box<CommError>> to substitute the Result<(), CommonError> to avoid the result-large-err warning.
As the [issue](https://github.com/robustmq/robustmq/issues/1114) discussed, this PR fixes the result_large_err warning in clippy
=> refactor: Use Box<CommonError> to fix the result_large_err warning in clippy.

.github/workflows/code-style.yml, codecheck.sh, example/single-mqtt-cluster/journal-server/journal-tracing.toml, example/single-mqtt-cluster/mqtt-server/mqtt-tracing.toml, example/single-mqtt-cluster/placement-center/place-tracing.toml
chore: synchronize new configuration in single-cluster and remove lint allow rules
Remove lint allow rule according: #1259
=> chore: synchronize new configuration in single-cluster and remove lint allow rules

docs/en/Architect/Broker-Server.md, docs/en/OverView/What-is-RobustMQ.md, docs/en/index.md, docs/zh/Architect/Broker-Server.md, docs/zh/OverView/What-is-RobustMQ.md, docs/zh/index.md
=> docs: Fix OpenMessaging typo in a few places

.gitignore, src/common/base/src/metrics/gauge.rs, src/common/base/src/metrics/mod.rs, src/mqtt-broker/src/common/metrics_cache.rs, src/mqtt-broker/src/observability/metrics/server.rs
add connections metrics for mqtt-broker
simple example:
```plain text
broker.connections.num{connection_type="Tcp"} 1
......
```
=> feat: add connections metrics for mqtt-broker

src/journal-server/src/lib.rs
There is a wrong code in `journal-server`: 2 asynchronous functions are executed outside the async runtime, which will cause **panic**. I converged it to execute in the async runtime of `daemon_thread`
=> fix: fix the error of executing async task outside async runtime

src/mqtt-broker/src/handler/validator.rs
This check
https://github.com/robustmq/robustmq/blob/5c9639fd424194ad19dc581f2962894db729e624/src/mqtt-broker/src/handler/validator.rs#L291-L311
link to 
https://github.com/robustmq/robustmq/blob/5c0a1f92074597343f88adafcd09b35adb64d061/src/mqtt-broker/src/handler/content_type.rs#L33-L43
and 
https://github.com/robustmq/robustmq/blob/5c9639fd424194ad19dc581f2962894db729e624/src/mqtt-broker/src/handler/validator.rs#L239-L265
is the same format indicator check
Expect should check only once
=> chore: cleanup redundancy format indicator check

Cargo.lock, Cargo.toml, src/admin-server/src/server.rs
- Add static file serving capability for dashboard resources from ../docs/
- Implement SPA fallback handler for frontend routing support  
- Add tower-http fs feature for ServeDir functionality
- Enable single-binary deployment with embedded frontend
=> feat: add dashboard static file serving to admin HTTP server

docs/en/QuickGuide/Build-and-Package.md, docs/zh/QuickGuide/Build-and-Package.md
Supplement the dryness that needs to be installed in the Quick Start documentation
- install protoc
- Resolve  `failed to run custom build command for zstd-sysv2.0.15+zstd.1.5.7`
=> docs:install protoc and zstd
